# Generated by Django 3.0.3 on 2025-02-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Город', models.CharField(max_length=50)),
                ('Слаг', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
