# Generated by Django 3.0.3 on 2025-02-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='Город',
        ),
        migrations.RemoveField(
            model_name='city',
            name='Слаг',
        ),
        migrations.AddField(
            model_name='city',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='city',
            name='slug',
            field=models.CharField(blank=True, max_length=50, verbose_name='Слаг'),
        ),
    ]
